# Generated by Django 4.2.11 on 2024-04-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=30)),
                ('release_date', models.DateTimeField(verbose_name='release date')),
                ('genre', models.CharField(max_length=200)),
                ('duration', models.FloatField()),
            ],
        ),
    ]
